name: "CLDR Coverage"
description: "Test fonts for script and writing system coverage based on CLDR data"
# inputs:
#   args: # id
#     description: "Args to the Python script"
#     required: false
#     default: "these are test args"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - test args here

branding:
  icon: "type"
  color: "purple"
